### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by JohnFTitor** [gabyse1/leaderboard#3]
# Hello @gabyse1 👋🏻 

Your project is really well constructed in the way you handle errors and display personalized messages when the output doesn't match the expected. You did a great job.

## Suggestions

The only suggestion I want to comment on is here: 

https://github.com/gabyse1/leaderboard/blob/26be843f7f38d401cd8ce6234f52077302be23e3/src/index.js#L51-L52

- [x] I think you can use ```.then(response => response.json())``` when you're fetching the data instead of await again to parse the response. Since it is a promise, you can handle the data this way for better readability. 

# Closing 😸 

Please let me know If you have any questions about my suggestions. We're all here to learn so let's take advantage of different perspectives!
Cheers and happy coding! 👨🏻‍💻 

<img src="https://media2.giphy.com/media/fT3PPZwB2lZMk/giphy.gif"/>

**Comment by oyelakinG9** [comment]
## Good job @gabyse1 
Your code looks fine but I would recommend you use the module to make it more organized
![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

**Comment by gabyse1** [comment]
### Thank you for your suggestions.
I worked on them.
